#!/bin/bash
####################################################################
# Author:               Sandro Aguilar
# Date:                 March 20, 2020
# Class:                Coursera - Bash Scripting
# Description:          Interacting with the command line
####################################################################
# line="-----------------------------"
# echo "Starting at: $(date)"
# echo $line

# echo "UPTIME"
# uptime
# echo $line

# echo "FREE"
# free
# echo $line

# echo "WHO"
# who
# echo $line

# echo "Finishing at: $(date)"


# conditional statements
if grep "127.0.0.1" /etc/hosts; then
    echo "Everything ok"
else
    echo "ERROR! 127.0.0.1 is not in /etc/hosts"




