#!/bin/bash
####################################################################
# Author:               Sandro Aguilar
# Date:                 March 20, 2020
# Class:                Coursera - Bash Scripting
# Description:          Interacting with the command line
####################################################################
# line="-----------------------------"
# echo "Starting at: $(date)"
# echo $line

# echo "UPTIME"
# uptime
# echo $line

# echo "FREE"
# free
# echo $line

# echo "WHO"
# who
# echo $line

# echo "Finishing at: $(date)"


# conditional statements
if grep "127.0.0.1" /etc/hosts; then
    echo "Everything ok"
else
    echo "ERROR! 127.0.0.1 is not in /etc/hosts"
fi

if test -n "$PATH"; then
    echo "Your path is not empty"
fi

# while loops
# n=1
# while [ $n -le 5 ]; do
#     echo "Iteration number $n"
#     ((n+=1))
# done

# n=0
# command=$1
# while ! $command && [ $n -le 5 ]; do
#     sleep $n
#     ((n=n+1))
#     echo "Retry #$n"
# done;


# for loops




















