#!/bin/bash
####################################################################
# Author:               Sandro Aguilar
# Date:                 March 20, 2020
# Class:                Coursera - Bash Scripting
# Description:          Interacting with the command line
####################################################################

























