#!/bin/bash

function push_commit()
{
    git commit -am bash
    git push
}


# what to run
if [ "$1" == 'push' ]; then
    # call function
    push_commit
    exit 0

elif [ "$1" == 'run' ]; then
    # run Python script
    python3 rename_file.py
    # push code
    push_commit
    exit 0

fi
