#!/bin/bash

function push_commit()
{
    git commit -am bash
    git push
}


# what to run
if [ "$1" == 'push' ]; then
    # call function
    push_commit
    exit 0

elif [ "$1" == 'runs' ]; then
    # push
    push_commit
    # run Python script
    python3 os_scripts.py
    exit 0

elif [ "$1" == 'run' ]; then
    # run Python script
    python3 os_scripts.py
    exit 0

fi
